spring:
  datasource.url: jdbc:${DATABASE_SOURCE}
  datasource.username: ${DATABASE_USERNAME}
  datasource.password: ${DATABASE_PASSWORD}
  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    debug: true
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true


app:
  email: ${MAIL_USERNAME}
  baseUrl: https://unitrack.bash.ip-ddns.com

server.port: 8081
