name: publish.yml
on:
  push:
    branches: [ master, main ]

jobs:

  check-lint:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_SMTP_AUTH: ${{ secrets.MAIL_SMTP_AUTH }}
      MAIL_SMTP_STARTTLS_ENABLE: ${{ secrets.MAIL_SMTP_STARTTLS_ENABLE }}

      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION_MS: ${{ secrets.JWT_EXPIRATION_MS }}
      JWT_REFRESH_EXPIRATION_MS: ${{ secrets.JWT_REFRESH_EXPIRATION_MS }}
      JWT_ISSUER: ${{ secrets.JWT_ISSUER }}

      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      BASE_URL: ${{ secrets.BASE_URL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.20.0
        with:
          distribution: temurin
          java-version: 21

      - name: Run lint
        run: mvn clean verify


  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: mvn clean -DskipTests package --file pom.xml

      - run: echo "Hello world"
      - name: Build Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: false
          tags: xanderj4/uni-track:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: xanderj4
          password: dckr_pat_D3PK-MIQUQdHywxlSrk3gSlKrxk

      - name: Push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: xanderj4/uni-track:latest
    needs:
      - check-lint